---
title: "CodeBook"
author: "Rathimala"
date: "Sunday, January 25, 2015"
output: pdf_document
---
Getting and Cleaning Data - Course Project Code Book

Data source:  https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

Variables:
[1] "activity"                             "subject"                             
[3] "tBodyAcc-mean-X"                      "tBodyAcc-mean-Y"                     
[5] "tBodyAcc-mean-Z"                      "tGravityAcc-mean-X"                  
[7] "tGravityAcc-mean-Y"                   "tGravityAcc-mean-Z"                  
[9] "tBodyAccJerk-mean-X"                  "tBodyAccJerk-mean-Y"                 
[11] "tBodyAccJerk-mean-Z"                  "tBodyGyro-mean-X"                    
[13] "tBodyGyro-mean-Y"                     "tBodyGyro-mean-Z"                    
[15] "tBodyGyroJerk-mean-X"                 "tBodyGyroJerk-mean-Y"                
[17] "tBodyGyroJerk-mean-Z"                 "tBodyAccMag-mean"                    
[19] "tGravityAccMag-mean"                  "tBodyAccJerkMag-mean"                
[21] "tBodyGyroMag-mean"                    "tBodyGyroJerkMag-mean"               
[23] "fBodyAcc-mean-X"                      "fBodyAcc-mean-Y"                     
[25] "fBodyAcc-mean-Z"                      "fBodyAcc-meanFreq-X"                 
[27] "fBodyAcc-meanFreq-Y"                  "fBodyAcc-meanFreq-Z"                 
[29] "fBodyAccJerk-mean-X"                  "fBodyAccJerk-mean-Y"                 
[31] "fBodyAccJerk-mean-Z"                  "fBodyAccJerk-meanFreq-X"             
[33] "fBodyAccJerk-meanFreq-Y"              "fBodyAccJerk-meanFreq-Z"             
[35] "fBodyGyro-mean-X"                     "fBodyGyro-mean-Y"                    
[37] "fBodyGyro-mean-Z"                     "fBodyGyro-meanFreq-X"                
[39] "fBodyGyro-meanFreq-Y"                 "fBodyGyro-meanFreq-Z"                
[41] "fBodyAccMag-mean"                     "fBodyAccMag-meanFreq"                
[43] "fBodyBodyAccJerkMag-mean"             "fBodyBodyAccJerkMag-meanFreq"        
[45] "fBodyBodyGyroMag-mean"                "fBodyBodyGyroMag-meanFreq"           
[47] "fBodyBodyGyroJerkMag-mean"            "fBodyBodyGyroJerkMag-meanFreq"       
[49] "angle(tBodyAccMean,gravity)"          "angle(tBodyAccJerkMean),gravityMean)"
[51] "angle(tBodyGyroMean,gravityMean)"     "angle(tBodyGyroJerkMean,gravityMean)"
[53] "angle(X,gravityMean)"                 "angle(Y,gravityMean)"                
[55] "angle(Z,gravityMean)"                 "tBodyAcc-std-X"                      
[57] "tBodyAcc-std-Y"                       "tBodyAcc-std-Z"                      
[59] "tGravityAcc-std-X"                    "tGravityAcc-std-Y"                   
[61] "tGravityAcc-std-Z"                    "tBodyAccJerk-std-X"                  
[63] "tBodyAccJerk-std-Y"                   "tBodyAccJerk-std-Z"                  
[65] "tBodyGyro-std-X"                      "tBodyGyro-std-Y"                     
[67] "tBodyGyro-std-Z"                      "tBodyGyroJerk-std-X"                 
[69] "tBodyGyroJerk-std-Y"                  "tBodyGyroJerk-std-Z"                 
[71] "tBodyAccMag-std"                      "tGravityAccMag-std"                  
[73] "tBodyAccJerkMag-std"                  "tBodyGyroMag-std"                    
[75] "tBodyGyroJerkMag-std"                 "fBodyAcc-std-X"                      
[77] "fBodyAcc-std-Y"                       "fBodyAcc-std-Z"                      
[79] "fBodyAccJerk-std-X"                   "fBodyAccJerk-std-Y"                  
[81] "fBodyAccJerk-std-Z"                   "fBodyGyro-std-X"                     
[83] "fBodyGyro-std-Y"                      "fBodyGyro-std-Z"                     
[85] "fBodyAccMag-std"                      "fBodyBodyAccJerkMag-std"             
[87] "fBodyBodyGyroMag-std"                 "fBodyBodyGyroJerkMag-std"


Subject
The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years.

Activity 
Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING)


The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag

The set of variables that were estimated from these signals are: 

mean(): Mean value
std(): Standard deviation








